apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: petsi
    meta.helm.sh/release-namespace: default
  labels:
    app: petsi
    app.kubernetes.io/instance: petsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: petsi-back
    app.kubernetes.io/version: 1.16.0
    env: dev
    helm.sh/chart: petsi-back-0.1.0
  name: petsi-petsi-back-v2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: petsi
      app.kubernetes.io/name: petsi-back
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: petsi
        app.kubernetes.io/name: petsi-back
        color: green
    spec:
      containers:
      - image: souheilbenslama/petpp:4
        imagePullPolicy: IfNotPresent
        name: petsi-back
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: petsi-petsi-back
      serviceAccountName: petsi-petsi-back
      terminationGracePeriodSeconds: 30

